// <auto-generated />
using System;
using FamilyMealFavoites.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FamilyMealFavoites.Migrations
{
    [DbContext(typeof(FamilyFavoritesDbContext))]
    [Migration("20181103232159_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FamilyMealFavoites.Models.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("FamilyMealFavoites.Models.AccountMenu", b =>
                {
                    b.Property<int>("MenuID");

                    b.Property<int>("AccountID");

                    b.HasKey("MenuID", "AccountID");

                    b.HasIndex("AccountID");

                    b.ToTable("AccountMenus");
                });

            modelBuilder.Entity("FamilyMealFavoites.Models.Ingredient", b =>
                {
                    b.Property<string>("IngredientType")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MenuID");

                    b.HasKey("IngredientType");

                    b.HasIndex("MenuID");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("FamilyMealFavoites.Models.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvgRating");

                    b.Property<string>("DishName");

                    b.HasKey("ID");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("FamilyMealFavoites.Models.MenuRating", b =>
                {
                    b.Property<int>("MenuID");

                    b.Property<int>("UserID");

                    b.Property<int>("Rating");

                    b.HasKey("MenuID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("MenuRatings");
                });

            modelBuilder.Entity("FamilyMealFavoites.Models.User", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountMenuAccountID");

                    b.Property<int?>("AccountMenuMenuID");

                    b.Property<string>("FirstName");

                    b.Property<string>("Lastname");

                    b.Property<string>("Password");

                    b.Property<int>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("AccountID");

                    b.HasIndex("AccountMenuMenuID", "AccountMenuAccountID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FamilyMealFavoites.Models.AccountMenu", b =>
                {
                    b.HasOne("FamilyMealFavoites.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FamilyMealFavoites.Models.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FamilyMealFavoites.Models.Ingredient", b =>
                {
                    b.HasOne("FamilyMealFavoites.Models.Menu")
                        .WithMany("Ingredients")
                        .HasForeignKey("MenuID");
                });

            modelBuilder.Entity("FamilyMealFavoites.Models.MenuRating", b =>
                {
                    b.HasOne("FamilyMealFavoites.Models.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FamilyMealFavoites.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FamilyMealFavoites.Models.User", b =>
                {
                    b.HasOne("FamilyMealFavoites.Models.AccountMenu")
                        .WithMany("Users")
                        .HasForeignKey("AccountMenuMenuID", "AccountMenuAccountID");
                });
#pragma warning restore 612, 618
        }
    }
}
